/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Global Macroeconomic and Market Dashboard API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod";

/**
 * @summary Health check
 */
export const HealthCheckResponse = zod.object({
  status: zod.string(),
});

/**
 * @summary Get stock indices data
 */
export const GetStockIndicesResponseItem = zod.object({
  symbol: zod.string(),
  name: zod.string(),
  price: zod.number(),
  change: zod.number(),
  changePercent: zod.number(),
  changePercentWeek: zod.number(),
  high52w: zod.number().nullish(),
  low52w: zod.number().nullish(),
  volume: zod.number().nullish(),
  marketCap: zod.number().nullish(),
  currency: zod.string(),
  region: zod.string(),
  googleFinanceUrl: zod.string(),
  isHighVolatility: zod.boolean(),
  alertLevel: zod.enum(["none", "watch", "alert", "critical"]),
  lastUpdated: zod.string(),
});
export const GetStockIndicesResponse = zod.array(GetStockIndicesResponseItem);

/**
 * @summary Get commodities data
 */
export const GetCommoditiesResponseItem = zod.object({
  symbol: zod.string(),
  name: zod.string(),
  price: zod.number(),
  change: zod.number(),
  changePercent: zod.number(),
  changePercentWeek: zod.number(),
  high52w: zod.number().nullish(),
  low52w: zod.number().nullish(),
  volume: zod.number().nullish(),
  marketCap: zod.number().nullish(),
  currency: zod.string(),
  region: zod.string(),
  googleFinanceUrl: zod.string(),
  isHighVolatility: zod.boolean(),
  alertLevel: zod.enum(["none", "watch", "alert", "critical"]),
  lastUpdated: zod.string(),
});
export const GetCommoditiesResponse = zod.array(GetCommoditiesResponseItem);

/**
 * @summary Get OHLC chart data for a symbol over a given time range
 */
export const GetMarketChartQueryParams = zod.object({
  symbol: zod.coerce.string(),
  range: zod.enum(["1h", "1d", "1w", "1m", "6m", "1yr", "5yr"]),
});

export const GetMarketChartResponse = zod.object({
  symbol: zod.string(),
  range: zod.string(),
  points: zod.array(
    zod.object({
      t: zod.number().describe("Unix timestamp in milliseconds"),
      o: zod.number().optional().describe("Open price"),
      h: zod.number().optional().describe("High price"),
      l: zod.number().optional().describe("Low price"),
      c: zod.number().describe("Close price"),
      v: zod.number().optional().describe("Volume"),
    }),
  ),
});

/**
 * Returns data for corn, wheat, soybeans, coffee, sugar, cotton, cocoa, live cattle, and lean hogs
 * @summary Get agricultural commodities data
 */
export const GetAgriculturalCommoditiesResponseItem = zod.object({
  symbol: zod.string(),
  name: zod.string(),
  price: zod.number(),
  change: zod.number(),
  changePercent: zod.number(),
  changePercentWeek: zod.number(),
  high52w: zod.number().nullish(),
  low52w: zod.number().nullish(),
  volume: zod.number().nullish(),
  marketCap: zod.number().nullish(),
  currency: zod.string(),
  region: zod.string(),
  googleFinanceUrl: zod.string(),
  isHighVolatility: zod.boolean(),
  alertLevel: zod.enum(["none", "watch", "alert", "critical"]),
  lastUpdated: zod.string(),
});
export const GetAgriculturalCommoditiesResponse = zod.array(
  GetAgriculturalCommoditiesResponseItem,
);

/**
 * @summary Get currency pairs data
 */
export const GetCurrenciesResponseItem = zod.object({
  symbol: zod.string(),
  name: zod.string(),
  price: zod.number(),
  change: zod.number(),
  changePercent: zod.number(),
  changePercentWeek: zod.number(),
  high52w: zod.number().nullish(),
  low52w: zod.number().nullish(),
  volume: zod.number().nullish(),
  marketCap: zod.number().nullish(),
  currency: zod.string(),
  region: zod.string(),
  googleFinanceUrl: zod.string(),
  isHighVolatility: zod.boolean(),
  alertLevel: zod.enum(["none", "watch", "alert", "critical"]),
  lastUpdated: zod.string(),
});
export const GetCurrenciesResponse = zod.array(GetCurrenciesResponseItem);

/**
 * @summary Get macroeconomic data (US, legacy)
 */
export const GetMacroDataResponse = zod.object({
  interestRates: zod.array(
    zod.object({
      id: zod.string(),
      name: zod.string(),
      value: zod.number(),
      previousValue: zod.number(),
      change: zod.number(),
      unit: zod.string(),
      frequency: zod.string(),
      lastUpdated: zod.string(),
      category: zod.enum([
        "interest_rate",
        "inflation",
        "gdp",
        "employment",
        "sentiment",
      ]),
      country: zod.string(),
    }),
  ),
  inflation: zod.array(
    zod.object({
      id: zod.string(),
      name: zod.string(),
      value: zod.number(),
      previousValue: zod.number(),
      change: zod.number(),
      unit: zod.string(),
      frequency: zod.string(),
      lastUpdated: zod.string(),
      category: zod.enum([
        "interest_rate",
        "inflation",
        "gdp",
        "employment",
        "sentiment",
      ]),
      country: zod.string(),
    }),
  ),
  gdp: zod.array(
    zod.object({
      id: zod.string(),
      name: zod.string(),
      value: zod.number(),
      previousValue: zod.number(),
      change: zod.number(),
      unit: zod.string(),
      frequency: zod.string(),
      lastUpdated: zod.string(),
      category: zod.enum([
        "interest_rate",
        "inflation",
        "gdp",
        "employment",
        "sentiment",
      ]),
      country: zod.string(),
    }),
  ),
  sentiment: zod.array(
    zod.object({
      id: zod.string(),
      name: zod.string(),
      value: zod.number(),
      previousValue: zod.number(),
      change: zod.number(),
      unit: zod.string(),
      frequency: zod.string(),
      lastUpdated: zod.string(),
      category: zod.enum([
        "interest_rate",
        "inflation",
        "gdp",
        "employment",
        "sentiment",
      ]),
      country: zod.string(),
    }),
  ),
});

/**
 * @summary Get macroeconomic data for a specific country
 */
export const GetMacroByCountryParams = zod.object({
  countryId: zod.enum(["usa", "uk", "canada", "eu"]),
});

export const GetMacroByCountryResponse = zod.object({
  interestRates: zod.array(
    zod.object({
      id: zod.string(),
      name: zod.string(),
      value: zod.number(),
      previousValue: zod.number(),
      change: zod.number(),
      unit: zod.string(),
      frequency: zod.string(),
      lastUpdated: zod.string(),
      category: zod.enum([
        "interest_rate",
        "inflation",
        "gdp",
        "employment",
        "sentiment",
      ]),
      country: zod.string(),
    }),
  ),
  inflation: zod.array(
    zod.object({
      id: zod.string(),
      name: zod.string(),
      value: zod.number(),
      previousValue: zod.number(),
      change: zod.number(),
      unit: zod.string(),
      frequency: zod.string(),
      lastUpdated: zod.string(),
      category: zod.enum([
        "interest_rate",
        "inflation",
        "gdp",
        "employment",
        "sentiment",
      ]),
      country: zod.string(),
    }),
  ),
  gdp: zod.array(
    zod.object({
      id: zod.string(),
      name: zod.string(),
      value: zod.number(),
      previousValue: zod.number(),
      change: zod.number(),
      unit: zod.string(),
      frequency: zod.string(),
      lastUpdated: zod.string(),
      category: zod.enum([
        "interest_rate",
        "inflation",
        "gdp",
        "employment",
        "sentiment",
      ]),
      country: zod.string(),
    }),
  ),
  sentiment: zod.array(
    zod.object({
      id: zod.string(),
      name: zod.string(),
      value: zod.number(),
      previousValue: zod.number(),
      change: zod.number(),
      unit: zod.string(),
      frequency: zod.string(),
      lastUpdated: zod.string(),
      category: zod.enum([
        "interest_rate",
        "inflation",
        "gdp",
        "employment",
        "sentiment",
      ]),
      country: zod.string(),
    }),
  ),
});

/**
 * @summary Get market summary
 */
export const GetMarketSummaryResponse = zod.object({
  topGainers: zod.array(
    zod.object({
      symbol: zod.string(),
      name: zod.string(),
      price: zod.number(),
      change: zod.number(),
      changePercent: zod.number(),
      changePercentWeek: zod.number(),
      high52w: zod.number().nullish(),
      low52w: zod.number().nullish(),
      volume: zod.number().nullish(),
      marketCap: zod.number().nullish(),
      currency: zod.string(),
      region: zod.string(),
      googleFinanceUrl: zod.string(),
      isHighVolatility: zod.boolean(),
      alertLevel: zod.enum(["none", "watch", "alert", "critical"]),
      lastUpdated: zod.string(),
    }),
  ),
  topLosers: zod.array(
    zod.object({
      symbol: zod.string(),
      name: zod.string(),
      price: zod.number(),
      change: zod.number(),
      changePercent: zod.number(),
      changePercentWeek: zod.number(),
      high52w: zod.number().nullish(),
      low52w: zod.number().nullish(),
      volume: zod.number().nullish(),
      marketCap: zod.number().nullish(),
      currency: zod.string(),
      region: zod.string(),
      googleFinanceUrl: zod.string(),
      isHighVolatility: zod.boolean(),
      alertLevel: zod.enum(["none", "watch", "alert", "critical"]),
      lastUpdated: zod.string(),
    }),
  ),
  highVolatility: zod.array(
    zod.object({
      symbol: zod.string(),
      name: zod.string(),
      price: zod.number(),
      change: zod.number(),
      changePercent: zod.number(),
      changePercentWeek: zod.number(),
      high52w: zod.number().nullish(),
      low52w: zod.number().nullish(),
      volume: zod.number().nullish(),
      marketCap: zod.number().nullish(),
      currency: zod.string(),
      region: zod.string(),
      googleFinanceUrl: zod.string(),
      isHighVolatility: zod.boolean(),
      alertLevel: zod.enum(["none", "watch", "alert", "critical"]),
      lastUpdated: zod.string(),
    }),
  ),
  alerts: zod.array(
    zod.object({
      symbol: zod.string(),
      name: zod.string(),
      message: zod.string(),
      severity: zod.enum(["watch", "alert", "critical"]),
      changePercent: zod.number(),
    }),
  ),
  overallSentiment: zod.enum(["bullish", "neutral", "bearish"]),
  lastUpdated: zod.string(),
});

/**
 * @summary Get weekly sparkline data for a list of symbols
 */
export const GetSparklinesQueryParams = zod.object({
  symbols: zod.coerce
    .string()
    .describe("Comma-separated list of ticker symbols"),
});

export const GetSparklinesResponseItem = zod.object({
  symbol: zod.string(),
  closes: zod.array(zod.number()),
});
export const GetSparklinesResponse = zod.array(GetSparklinesResponseItem);

/**
 * Returns per-stock fundamental and technical indicators for the given index
 * @summary Get detailed stock data for a specific index
 */
export const GetIndexStocksParams = zod.object({
  indexId: zod.enum([
    "nasdaq",
    "dowjones",
    "tsx",
    "ftse100",
    "dax",
    "hangseng",
  ]),
});

export const GetIndexStocksResponse = zod.object({
  indexId: zod.string(),
  indexName: zod.string(),
  stocks: zod.array(
    zod.object({
      symbol: zod.string(),
      name: zod.string(),
      price: zod.number(),
      change: zod.number(),
      changePercent: zod.number(),
      changePercentWeek: zod.number(),
      marketCap: zod.number().nullish(),
      volume: zod.number().nullish(),
      currency: zod.string(),
      high52w: zod.number().nullish(),
      low52w: zod.number().nullish(),
      isNearATH: zod.boolean(),
      isNearATL: zod.boolean(),
      googleFinanceUrl: zod.string(),
      alertLevel: zod.enum(["none", "watch", "alert", "critical"]),
      peRatio: zod.number().nullish(),
      forwardPE: zod.number().nullish(),
      pegRatio: zod.number().nullish(),
      pbRatio: zod.number().nullish(),
      deRatio: zod.number().nullish(),
      roe: zod.number().nullish(),
      dividendYield: zod.number().nullish(),
      rsi14: zod.number().nullish(),
      ma20: zod.number().nullish(),
      ma50: zod.number().nullish(),
      ma200: zod.number().nullish(),
      priceVsMa20: zod.enum(["above", "below", "na"]),
      priceVsMa50: zod.enum(["above", "below", "na"]),
      priceVsMa200: zod.enum(["above", "below", "na"]),
      qualityScore: zod.number(),
      qualityLabel: zod.enum(["excellent", "good", "fair", "poor"]),
      sparkline: zod
        .array(zod.number())
        .describe("Last 7 daily closing prices for chart rendering"),
      lastUpdated: zod.string(),
    }),
  ),
  lastUpdated: zod.string(),
});
