/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Global Macroeconomic and Market Dashboard API
 * OpenAPI spec version: 0.1.0
 */

export interface ChartPoint {
  /** Unix timestamp in milliseconds */
  t: number;
  /** Open price */
  o?: number;
  /** High price */
  h?: number;
  /** Low price */
  l?: number;
  /** Close price */
  c: number;
  /** Volume */
  v?: number;
}
