/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Global Macroeconomic and Market Dashboard API
 * OpenAPI spec version: 0.1.0
 */

export type GetMarketChartRange =
  (typeof GetMarketChartRange)[keyof typeof GetMarketChartRange];

export const GetMarketChartRange = {
  "1h": "1h",
  "1d": "1d",
  "1w": "1w",
  "1m": "1m",
  "6m": "6m",
  "1yr": "1yr",
  "5yr": "5yr",
} as const;
