/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Global Macroeconomic and Market Dashboard API
 * OpenAPI spec version: 0.1.0
 */
import type { IndexStockAlertLevel } from "./indexStockAlertLevel";
import type { IndexStockPriceVsMa20 } from "./indexStockPriceVsMa20";
import type { IndexStockPriceVsMa200 } from "./indexStockPriceVsMa200";
import type { IndexStockPriceVsMa50 } from "./indexStockPriceVsMa50";
import type { IndexStockQualityLabel } from "./indexStockQualityLabel";

export interface IndexStock {
  symbol: string;
  name: string;
  price: number;
  change: number;
  changePercent: number;
  changePercentWeek: number;
  marketCap?: number | null;
  volume?: number | null;
  currency: string;
  high52w?: number | null;
  low52w?: number | null;
  isNearATH: boolean;
  isNearATL: boolean;
  googleFinanceUrl: string;
  alertLevel: IndexStockAlertLevel;
  peRatio?: number | null;
  forwardPE?: number | null;
  pegRatio?: number | null;
  pbRatio?: number | null;
  deRatio?: number | null;
  roe?: number | null;
  dividendYield?: number | null;
  rsi14?: number | null;
  ma20?: number | null;
  ma50?: number | null;
  ma200?: number | null;
  priceVsMa20: IndexStockPriceVsMa20;
  priceVsMa50: IndexStockPriceVsMa50;
  priceVsMa200: IndexStockPriceVsMa200;
  qualityScore: number;
  qualityLabel: IndexStockQualityLabel;
  /** Last 7 daily closing prices for chart rendering */
  sparkline: number[];
  lastUpdated: string;
}
