/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Global Macroeconomic and Market Dashboard API
 * OpenAPI spec version: 0.1.0
 */

export type IndexStockPriceVsMa20 =
  (typeof IndexStockPriceVsMa20)[keyof typeof IndexStockPriceVsMa20];

export const IndexStockPriceVsMa20 = {
  above: "above",
  below: "below",
  na: "na",
} as const;
