/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Global Macroeconomic and Market Dashboard API
 * OpenAPI spec version: 0.1.0
 */

export type IndexStockPriceVsMa50 =
  (typeof IndexStockPriceVsMa50)[keyof typeof IndexStockPriceVsMa50];

export const IndexStockPriceVsMa50 = {
  above: "above",
  below: "below",
  na: "na",
} as const;
