/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Global Macroeconomic and Market Dashboard API
 * OpenAPI spec version: 0.1.0
 */

export type IndexStockAlertLevel =
  (typeof IndexStockAlertLevel)[keyof typeof IndexStockAlertLevel];

export const IndexStockAlertLevel = {
  none: "none",
  watch: "watch",
  alert: "alert",
  critical: "critical",
} as const;
