/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Global Macroeconomic and Market Dashboard API
 * OpenAPI spec version: 0.1.0
 */

export type IndexStockPriceVsMa200 =
  (typeof IndexStockPriceVsMa200)[keyof typeof IndexStockPriceVsMa200];

export const IndexStockPriceVsMa200 = {
  above: "above",
  below: "below",
  na: "na",
} as const;
