/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Global Macroeconomic and Market Dashboard API
 * OpenAPI spec version: 0.1.0
 */
import type { MacroIndicatorCategory } from "./macroIndicatorCategory";

export interface MacroIndicator {
  id: string;
  name: string;
  value: number;
  previousValue: number;
  change: number;
  unit: string;
  frequency: string;
  lastUpdated: string;
  category: MacroIndicatorCategory;
  country: string;
}
