/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Global Macroeconomic and Market Dashboard API
 * OpenAPI spec version: 0.1.0
 */
import type { MarketAlertSeverity } from "./marketAlertSeverity";

export interface MarketAlert {
  symbol: string;
  name: string;
  message: string;
  severity: MarketAlertSeverity;
  changePercent: number;
}
