/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Global Macroeconomic and Market Dashboard API
 * OpenAPI spec version: 0.1.0
 */
import type { MarketAlert } from "./marketAlert";
import type { MarketSummaryOverallSentiment } from "./marketSummaryOverallSentiment";
import type { MarketTicker } from "./marketTicker";

export interface MarketSummary {
  topGainers: MarketTicker[];
  topLosers: MarketTicker[];
  highVolatility: MarketTicker[];
  alerts: MarketAlert[];
  overallSentiment: MarketSummaryOverallSentiment;
  lastUpdated: string;
}
