/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Global Macroeconomic and Market Dashboard API
 * OpenAPI spec version: 0.1.0
 */

export type MarketAlertSeverity =
  (typeof MarketAlertSeverity)[keyof typeof MarketAlertSeverity];

export const MarketAlertSeverity = {
  watch: "watch",
  alert: "alert",
  critical: "critical",
} as const;
