/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Global Macroeconomic and Market Dashboard API
 * OpenAPI spec version: 0.1.0
 */

export type MarketSummaryOverallSentiment =
  (typeof MarketSummaryOverallSentiment)[keyof typeof MarketSummaryOverallSentiment];

export const MarketSummaryOverallSentiment = {
  bullish: "bullish",
  neutral: "neutral",
  bearish: "bearish",
} as const;
