/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Global Macroeconomic and Market Dashboard API
 * OpenAPI spec version: 0.1.0
 */
import type { MarketTickerAlertLevel } from "./marketTickerAlertLevel";

export interface MarketTicker {
  symbol: string;
  name: string;
  price: number;
  change: number;
  changePercent: number;
  changePercentWeek: number;
  high52w?: number | null;
  low52w?: number | null;
  volume?: number | null;
  marketCap?: number | null;
  currency: string;
  region: string;
  googleFinanceUrl: string;
  isHighVolatility: boolean;
  alertLevel: MarketTickerAlertLevel;
  lastUpdated: string;
}
